# Generated by Django 4.2.15 on 2024-08-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_user_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
