# Generated by Django 4.2.15 on 2024-08-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_user_create_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
