# Generated by Django 4.2.15 on 2024-08-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['created_date']},
        ),
    ]
